config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :books
      resources :authors do
        resources :books
      end
      resources :genres do
        resources :books
      end
      resources :subscribers do
        resources :subscriptions
      end
    end
    namespace :admin do
      resources :authors
      resources :genres do
        resources :books
      end
      resources :books
      resources :subscribers do
        resources :subscriptions
      end
      resources :subscriptions
    end
  end
  # resources :subscriptions
  # resources :subscribersw
  # resources :authors
  # resources :books
  # resources :genres
end

app/models/authors_book.rb
# frozen_string_literal: true

class AuthorsBook < ApplicationRecord
  belongs_to :author
  belongs_to :book

  validates :author_id, presence: true
  validates :book_id, presence: true, uniqueness: { scope: :author_id }
end

app/helpers/authors_books_helper.rb
# frozen_string_literal: true

module AuthorsBooksHelper
end

app/views/authors_books/_form.html.erb
<%= form_with(model: authors_book) do |form| %>
  <% if authors_book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(authors_book.errors.count, "error") %> prohibited this authors_book from being saved:</h2>

      <ul>
        <% authors_book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :authors_id, style: "display: block" %>
    <%= form.text_field :authors_id %>
  </div>

  <div>
    <%= form.label :books_id, style: "display: block" %>
    <%= form.text_field :books_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/authors_books/edit.html.erb
<h1>Editing authors book</h1>

<%= render "form", authors_book: @authors_book %>

<br>

<div>
  <%= link_to "Show this authors book", @authors_book %> |
  <%= link_to "Back to authors books", authors_books_path %>
</div>

app/views/authors_books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Authors books</h1>

<div id="authors_books">
  <% @authors_books.each do |authors_book| %>
    <%= render authors_book %>
    <p>
      <%= link_to "Show this authors book", authors_book %>
    </p>
  <% end %>
</div>

<%= link_to "New authors book", new_authors_book_path %>

app/views/authors_books/new.html.erb
<h1>New authors book</h1>

<%= render "form", authors_book: @authors_book %>

<br>

<div>
  <%= link_to "Back to authors books", authors_books_path %>
</div>

app/views/authors_books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @authors_book %>

<div>
  <%= link_to "Edit this authors book", edit_authors_book_path(@authors_book) %> |
  <%= link_to "Back to authors books", authors_books_path %>

  <%= button_to "Destroy this authors book", @authors_book, method: :delete %>
</div>